spring:
  datasource:
    url: jdbc:postgresql://150.230.73.163:5432/academia
    username: postgres
    password: c3por2d2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
